db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rails s -p 4000 -b '0.0.0.0'
  volumes:
    - .:/oauth-client
  ports:
    - "4000:4000"
  links:
    - db
  volumes_from:
    - bundle
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
    - OAUTH_URL=https://b7ab98d5.ngrok.io/
    - OAUTH_ID=8353a61f1773539f553189812e3b5e56fcb71fd1ccd2896f2b8f3e925a09c321
    - OAUTH_SECRET=70e7899b4bbb1e3889fa4a0cc55c01a82a5c61454f372e2bad429e3c05edbf11
bundle:
  image: oauthclient_web
  volumes:
    - /bundle
