db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rails s -p 4000 -b '0.0.0.0'
  volumes:
    - .:/oauth-client
  ports:
    - "4000:4000"
  links:
    - db
  volumes_from:
    - bundle
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
    - OAUTH_URL=https://0529a6fe.ngrok.io
    - OAUTH_ID=ec5aa78511c60d39ff58ecab79516cb7098d7b04232715c04b915a04ba440543
    - OAUTH_SECRET=62a54ac8cf7cf0d8a3c15d3131157ee6da453da88ba87ffdbc216701e37221f0
bundle:
  image: oauthclient_web
  volumes:
    - /bundle
