db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rails s -p 4000 -b '0.0.0.0'
  volumes:
    - .:/oauth-client
  ports:
    - "4000:4000"
  links:
    - db
  volumes_from:
    - bundle
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
    - OAUTH_URL=https://740ed3dd.ngrok.io
bundle:
  image: oauthclient_web
  volumes:
    - /bundle
