db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rails s -p 4000 -b '0.0.0.0'
  volumes:
    - .:/oauth-client
  ports:
    - "4000:4000"
  links:
    - db
  volumes_from:
    - bundle
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
    - OAUTH_URL=https://740ed3dd.ngrok.io
    - OAUTH_ID=7a4ccbeb54864c38935c68fcbff39dcc9e06ef52b7313937db8130837f7a5f8b
    - OAUTH_SECRET=fa1bfd3844b85494a80151d61d0a01ee8fcf4aeb7e8c4defef2511e0cd4d187c
bundle:
  image: oauthclient_web
  volumes:
    - /bundle
