db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: bundle exec rails s -p 4000 -b '0.0.0.0'
  volumes:
    - .:/oauth-client
  ports:
    - "4000:4000"
  links:
    - db
  volumes_from:
    - bundle
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
    - OAUTH_URL=https://3cf4768a.ngrok.io
    - OAUTH_ID=b557c2d5367da43cb396192b778b9579ae582cba7d3d779a62e4f44751c7dded
    - OAUTH_SECRET=d6651176c393cb3a5f33a3dfbb84205f68579adce29e6f65f4b108c0b7b62eea
bundle:
  image: oauthclient_web
  volumes:
    - /bundle
